package proyecto2_edd;
import Estructuras.Lista;
import java.awt.Image;
import javax.swing.ImageIcon;
import Estructuras.TablaHash;
import Servidor.Server;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class Interfaz extends javax.swing.JFrame {
    private String DEFAULT_PORT="10101";
    private Server server;
    static TablaHash tablaUsuarios;
    static String carnetGeneralLogin;
    
    static String crearUsuarioLogin;
    static String concatenar;
    public Interfaz() {
        initComponents();
        ImageIcon imagen=new ImageIcon("C:\\Users\\SERGIO_RPR\\Documents\\NetBeansProjects\\PROYECTO2_EDD\\src\\Imagenes\\login.png");
        ImageIcon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        
        
        ImageIcon imagen2=new ImageIcon("C:\\Users\\SERGIO_RPR\\Documents\\NetBeansProjects\\PROYECTO2_EDD\\src\\Imagenes\\registro.png");
        ImageIcon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(imagenRegistroJlbl.getWidth(),imagenRegistroJlbl.getHeight(),Image.SCALE_DEFAULT));
        imagenRegistroJlbl.setIcon(icono2);
        
        
         
        ImageIcon imagen3=new ImageIcon("C:\\Users\\SERGIO_RPR\\Documents\\NetBeansProjects\\PROYECTO2_EDD\\src\\Imagenes\\libro.png");
        ImageIcon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance(jLabel10.getWidth(),jLabel10.getHeight(),Image.SCALE_DEFAULT));
        jLabel10.setIcon(icono3);
        //Instancia de tabla Hash
        tablaUsuarios = new TablaHash();
        crearUsuarioLogin="";
        concatenar="{\n\"CREAR_USUARIO\":[\n{\n";
       
        tablaUsuarios=new TablaHash();
        obtenerHora();
        String puerto=getPuerto();
        //server=new Server(puerto, this);
        
       
        
        
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imagenRegistroJlbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jlbMensaje = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        boxCarreras = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        txtPassword2 = new javax.swing.JPasswordField();
        jlbCargaDeDatos = new javax.swing.JLabel();
        jblConfiguracion = new javax.swing.JLabel();
        jblReportes1 = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("CARNET:");

        jLabel3.setText("PASSWORD:");

        imagenRegistroJlbl.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("REGISTRO DE USUARIOS");

        jLabel5.setText("CARNET:");

        jLabel6.setText("NOMBRE:");

        jLabel7.setText("APELLIDO:");

        jLabel8.setText("CARRERA:");

        jLabel9.setText("PASSWORD:");

        txtCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarreraActionPerformed(evt);
            }
        });

        jButton2.setText("REGISTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jlbMensaje.setFont(new java.awt.Font("Arial Black", 0, 8)); // NOI18N
        jlbMensaje.setForeground(new java.awt.Color(255, 0, 0));
        jlbMensaje.setText("mensaje");

        jLabel10.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("BIBLIOTECA VIRTUAL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("LOGIN");

        boxCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Ciencias y Sistemas", "Ingeniería Química", "Ingeniería Industrial", "Ingeniería Eléctrica", "Ingeniería Mecánica", "Ingeniería Mecánica Eléctrica", "Ingeniería Mecánica Industrial", "Ingeniería Civil", "Ingeniería Electrónica", "Ingeniería Ambiental", " " }));
        boxCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCarrerasActionPerformed(evt);
            }
        });

        jlbCargaDeDatos.setForeground(new java.awt.Color(0, 0, 255));
        jlbCargaDeDatos.setText("Carga de Datos");
        jlbCargaDeDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbCargaDeDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCargaDeDatosMouseClicked(evt);
            }
        });

        jblConfiguracion.setForeground(new java.awt.Color(0, 0, 255));
        jblConfiguracion.setText("Configuracion");
        jblConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jblReportes1.setForeground(new java.awt.Color(0, 0, 255));
        jblReportes1.setText("Reportes");
        jblReportes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblReportes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblReportes1MouseClicked(evt);
            }
        });

        jLabel13.setText("PUERTO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txtPassword)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jblConfiguracion)))
                                        .addGap(52, 52, 52)
                                        .addComponent(jblReportes1))
                                    .addComponent(txtPuerto)))
                            .addComponent(jlbCargaDeDatos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(imagenRegistroJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(txtCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(boxCarreras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPassword2))))
                    .addComponent(jlbMensaje))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(imagenRegistroJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCargaDeDatos)
                    .addComponent(jblConfiguracion)
                    .addComponent(jblReportes1)
                    .addComponent(jlbMensaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        carnetGeneralLogin=txtUsuario.getText();
        JOptionPane.showMessageDialog(this,carnetGeneralLogin,"MENSAJE",JOptionPane.INFORMATION_MESSAGE);
        
        boolean confirmar;
        String password=new String(txtPassword.getPassword());
        confirmar=tablaUsuarios.logearse(Integer.parseInt(txtUsuario.getText()), password);
        
        if(confirmar){
            new InterfazModulo2_Biblioteca().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Usuario y/o Password Incorrectas !","Error de Autentificacion",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarreraActionPerformed

    private void boxCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCarrerasActionPerformed
             txtCarrera.setText(boxCarreras.getSelectedItem().toString());       
        
    }//GEN-LAST:event_boxCarrerasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtCarnet.getText().length()==0 || txtNombre.getText().length() == 0 || txtApellido.getText().length() == 0 || txtCarrera.getText().length() == 0
          || txtPassword2.getPassword().length==0){
            jlbMensaje.setText("TODOS LOS CAMPOS SON OBLIGATORIOS");
        } 
        else{
             boolean band=false;
             if(txtCarnet.getText().length()!=9){
                  JOptionPane.showMessageDialog(this,"El carnet debe ser de 9 numeros !","MENSAJE",JOptionPane.ERROR_MESSAGE);
                  band=true;
             }
             if(txtCarnet.getText().length()>0){
                 for(int i=0; i<txtCarnet.getText().length();i++){
                     if(!isNumeric(Character.toString(txtCarnet.getText().charAt(i)))){
                         JOptionPane.showMessageDialog(this,"El carnet debe ser solo numeros !","MENSAJE",JOptionPane.ERROR_MESSAGE);
                         band=true; 
                         break;
                     }
                 }
             }
             if(tablaUsuarios.buscarCarnet(Integer.parseInt(txtCarnet.getText()))){
                         JOptionPane.showMessageDialog(this,"USUARIO YA REGISTRADO!","MENSAJE",JOptionPane.ERROR_MESSAGE);
                         band=true; 
                         
             }
             if(!band){
                   int carnet = Integer.parseInt(txtCarnet.getText());
                   String password = new String(txtPassword2.getPassword());
                   tablaUsuarios.agregar(carnet,txtNombre.getText(),txtApellido.getText(),txtCarrera.getText(),password);
                   JOptionPane.showMessageDialog(this,"Usuario Registrado Con Exito !","MENSAJE",JOptionPane.INFORMATION_MESSAGE);
                   
                   crearUsuarioLogin=crearUsuarioLogin+concatenar+"\"Carnet\":"+carnet+",\n"+"\"Nombre\":"+"\""+txtNombre.getText()+"\""+",\n"
                                                      +"\"Apellido\":"+"\""+txtApellido.getText()+"\""+",\n"+"\"Carrera\":"+"\""+txtCarrera.getText()+"\""+",\n"
                                                      +"\"Password\":"+"\""+password+"\""+"\n}\n]\n},";
             }
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed
  
    private static boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	}catch (NumberFormatException nfe){
		return false;
	}
     }
    private void jlbCargaDeDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCargaDeDatosMouseClicked
           new InterfazModulo1_CM().setVisible(true);
          
          //jlbMensaje.setText("SERGIO RIVELINO");
    }//GEN-LAST:event_jlbCargaDeDatosMouseClicked

    private void jblReportes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblReportes1MouseClicked
           new InterfazModulo3_Reportes().setVisible(true);
    }//GEN-LAST:event_jblReportes1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    void agregarLog(String texto){
        jlbMensaje.setText(texto);
    }
    private String getPuerto(){
        String p=DEFAULT_PORT;
        txtPuerto.setText(p);
        
        return p;
    }
    public void addServidorIniciado() {
        jlbMensaje.setText("Inicializando el servidor... [Ok].");
    }  
    public void obtenerHora(){
        Date date = new Date();
        DateFormat hora = new SimpleDateFormat("HH:MM:SS");
        DateFormat fecha = new SimpleDateFormat("DD-MM-YY");
        
        DateFormat fechaHora = new SimpleDateFormat("dd-MM-yy HH:mm:ss");
        System.out.println(fechaHora.format(date));
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCarreras;
    private javax.swing.JLabel imagenRegistroJlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jblConfiguracion;
    private javax.swing.JLabel jblReportes1;
    private javax.swing.JLabel jlbCargaDeDatos;
    private javax.swing.JLabel jlbMensaje;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
